In [2]:
import pandas as pd
dataset = pd.read_csv('data/db.csv', sep = ';')
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', 10)

#Tipos de dados
dataset.dtypes

# Estatística descritiva
dataset[['Quilometragem', 'Valor']].describe()

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

In [6]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
valores = [88078.64, 106161.94, 72832.16, 124549.07]

In [7]:
carros.index('Passat')
valores[carros.index('Passat')]

106161.94

In [8]:
list(zip(carros, valores))
dados = dict(zip(carros, valores))

In [9]:
dados.update({'Passat': 2000.33, 'Fusca': 150000})

In [10]:
dados.values()

dict_values([88078.64, 2000.33, 72832.16, 124549.07, 150000])

In [14]:
def media():
    return (1 + 2 + 3)/3

In [15]:
print(media())

2.0

In [16]:
teste  = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [45]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [55]:
def km_media(dataset, ano_atual):
    auxiliar = {}
    for item in dataset.items():
        auxiliar.update({item[0] : item[1]['km'] / (ano_atual - item[1]['ano'])})
        #print(item)
        
    return auxiliar
        
print(km_media(dados, 2019))

{'Crossfox': 2500.0, 'DS5': 4250.0, 'Fusca': 3250.0, 'Jetta': 7000.0, 'Passat': 3100.0}

In [16]:
import pandas as pd

carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
valores = [88078.64, 106161.94, 72832.16, 124549.07]

teste = pd.Series(carros)

dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

dataset = pd.DataFrame(dados)

,Nome,Motor,Ano,Quilometragem,Zero_km,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,0,88078.64
1,Jetta VariantPassat,Motor 4.0 TurboMotor Diesel,3994,50122.0,0,194240.58
2,Jetta VariantPassatCrossfox,Motor 4.0 TurboMotor DieselMotor Diesel V8,5984,87245.0,0,267072.74

In [85]:
dataset = pd.read_csv('data/db.csv', sep = ';', index_col = 0)
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [114]:
# dataset[0:3]
# dataset.loc[['Passat', 'DS5']]
# dataset.loc[['Passat', 'DS5']][['Motor','Valor']]
#dataset.iloc[[1]]
# dataset.iloc[1:4]
# dataset.iloc[1:4, [0,5, 2]]
# dataset.iloc[[1,44,22], [0,5, 2]]
# dataset.iloc[:, [0,5, 2]

# Seleção
## select = dataset.Motor == 'Motor Diesel' 
## dataset[select]


# seleção com 2 condições
## selecao = (dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)
## dataset[selecao]

##Seleção usando Query
# dataset.query('Motor == "Motor Diesel" and Zero_km == True')

# iteração
# list(dataset.iterrows())

# dataset.info()

# dataset[dataset.Quilometragem.isna()]

# Preenchidmento
# dataset.fillna(0,inplace = True)

dataset.query('Zero_km == True')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019,0.0,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019,0.0,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019,0.0,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019,0.0,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019,0.0,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,0.0,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019,0.0,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019,0.0,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019,0.0,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019,0.0,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [99]:
for index, row  in dataset.iterrows():
    Auxiliar = 2019 - row['Ano']
    
    if (Auxiliar == 0):
        dataset.loc[index, 'Km_media'] = 0
    else:      
        dataset.loc[index, 'Km_media'] = row['Quilometragem'] / Auxiliar

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019,NaN,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019,NaN,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019,NaN,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,NaN,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019,NaN,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019,NaN,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019,NaN,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019,NaN,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [116]:
dataset = pd.read_csv('data/db.csv', sep = ';')
dataset.dropna(subset = ['Quilometragem'], inplace = True) # Abordagem para Elimnar a coluna
dataset.fillna(0,inplace = True) # Abordagem para preencher com 0 colunas que estão com 0

In [117]:
dataset

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
5,Palio Weekend,Motor 1.8 16v,2012,10728.0,False,"['Sensor de estacionamento', 'Teto panorâmico'...",97497.73
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47